<?php

//this doesn't really do much except call the redirect function below
function bakery_user_menu() {
    $items = array();
    $items['welcome'] = array(
        'title' => 'Guestbook',
        'page callback' => 'bakery_user_user_login',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}


//I renamed the page you created ('welcome_new_user') to ('guestbook')
//to better represent what cameron wants
function bakery_user_user_login(&$edit, $account) {
    $_GET['destination'] = 'guestbook';
}
